<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Description>Library that transforms OFX files into .NET objects by stating only the file path.</Description>
    <Company>Leonardo Melo Santos</Company>
    <Product>OFXParser</Product>
    <Copyright>Copyright © 2025</Copyright>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
    <Version>2.0.0</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DocumentationFile>bin\Release\OFXParser.XML</DocumentationFile>
  </PropertyGroup>
</Project>
